### ISSUE TITLE
`await Page.captureScreenshot()` fails

### ISSUE THREAD

**Issue by pthieu** [cyrus-and/chrome-remote-interface#104]
According to http://www.zackarychapple.guru/chrome/2016/08/24/chrome-headless.html, `Page.captureScreenshot()` should return a promise, which means what we should be able to `await` it and assign the resolved data to some variable, but when doing the following line:

```
const ssData = await Page.captureScreenshot();
```

I get the error:
```
$ node chrome.js
    const ssData = await Page.captureScreenshot();
                         ^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
```

My env:
```
$ node -v
v7.9.0
$ uname -a
MINGW32_NT-6.2 PHONG-PC 1.0.12(0.46/3/2) 2012-07-05 14:56 i686 unknown
```
Probably not important but I'm using `Git for Windows` on `Windows 10`

Here's my test code:
```js
  const CDP = require('chrome-remote-interface');

  CDP(async(client) => {
    // extract domains
    const {
      Network,
      Page
    } = client;
    // setup handlers
    Network.requestWillBeSent((params) => {
      console.log(params.request.url);
    });
    Page.loadEventFired(() => {
      const ssData = await Page.captureScreenshot();
      await screenshot(ssData);
      client.close();
    });
    // enable events then start!
    try {
      await Promise.all([Network.enable(), Page.enable()]);
      await Page.navigate({
        url: 'https://github.com'
      });
    } catch (err) {
      console.error(err);
      client.close();
    }
  }).on('error', (err) => {
    // cannot connect to the remote endpoint
    console.error(err);
  });


  function screenshot(v) {
    return new Promise((resolve, reject) => {
      try {
        let filename = `screenshot-${Date.now()}`;
        fs.writeFileSync(filename + '.png', v.data, 'base64');
        console.log(`Image saved as ${filename}.png`);
        return resolve();
      } catch(e) {
        return reject(e);
      }
    });
  };
```

**Comment by pthieu** [comment]
Actually I think the issue may be that I have to define the anonymous function as async:

```
    Page.loadEventFired(async () => {
      const ssData = await Page.captureScreenshot();
      await screenshot(ssData);
      client.close();
    });
```

**Comment by cyrus-and** [comment]
Yes that's definitely it.
