### ISSUE TITLE
chrome-remote-interface inspect: TypeError: this is not a typed array.

### ISSUE THREAD

**Issue by d33tah** [cyrus-and/chrome-remote-interface#111]
```
[18:58:44] ➜  ~  chrome-remote-interface inspect   

/usr/local/lib/node_modules/chrome-remote-interface/node_modules/ws/lib/PerMessageDeflate.js:8
const TRAILER = Buffer.from([0x00, 0x00, 0xff, 0xff]);
                       ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/chrome-remote-interface/node_modules/ws/lib/PerMessageDeflate.js:8:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/chrome-remote-interface/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:410:26)
```

**Comment by cyrus-and** [comment]
You're likely using an old version of Node.js, see cyrus-and/chrome-har-capturer#38.
