### ISSUE TITLE
TypeError: Cannot read property 'protocol' of undefined

### ISSUE THREAD

**Issue by OkuyamaYuya** [cyrus-and/chrome-remote-interface#123]
I would like to use Google Chrome Canary as headless browser using chrome-remote-interface.
So, I try to execute a sample program:

```javascript:
const CDP = require('chrome-remote-interface');

CDP(client => {
    // extract domains
    const {Network, Page} = client;
    // setup handlers
    Network.requestWillBeSent((params) => {
        console.log(params.request.url);
    });
    Page.loadEventFired(() => {
        client.close();
    });
    // enable events then start!
    Promise.all([
        Network.enable(),
        Page.enable()
    ]).then(() => {
        return Page.navigate({url: 'https://github.com'});
    }).catch((err) => {
        console.error(err);
        client.close();
    });
}).on('error', (err) => {
    // cannot connect to the remote endpoint
    console.error(err);
});
```

But, this program fails and the following error occurs:

```
TypeError: Cannot read property 'protocol' of undefined
    at Object.s.request (/usr/local/Cellar/node/7.7.3/lib/node_modules/chrome-remote-interface/chrome-remote-interface.js:1:31755)
    at Object.s.get (/usr/local/Cellar/node/7.7.3/lib/node_modules/chrome-remote-interface/chrome-remote-interface.js:2:9)
    at n (/usr/local/Cellar/node/7.7.3/lib/node_modules/chrome-remote-interface/chrome-remote-interface.js:3:19736)
    at r (/usr/local/Cellar/node/7.7.3/lib/node_modules/chrome-remote-interface/chrome-remote-interface.js:1:6181)
    at /usr/local/Cellar/node/7.7.3/lib/node_modules/chrome-remote-interface/chrome-remote-interface.js:1:8789
    at /usr/local/Cellar/node/7.7.3/lib/node_modules/chrome-remote-interface/chrome-remote-interface.js:1:6334
    at Object.List (/usr/local/Cellar/node/7.7.3/lib/node_modules/chrome-remote-interface/chrome-remote-interface.js:1:6308)
    at /usr/local/Cellar/node/7.7.3/lib/node_modules/chrome-remote-interface/chrome-remote-interface.js:10:18087
    at t.c (/usr/local/Cellar/node/7.7.3/lib/node_modules/chrome-remote-interface/chrome-remote-interface.js:10:17750)
    at t.s (/usr/local/Cellar/node/7.7.3/lib/node_modules/chrome-remote-interface/chrome-remote-interface.js:10:17374)
```

For executing the above program, what should I do.

**Comment by cyrus-and** [comment]
That error happens because you're using `chrome-remote-interface.js` which is the web-packed version that only works in a browser context.

Said that, I don't know how you ended up using it... can you tell me a bit more about how you installed chrome-remote-interface and run the example?

From the stack trace it seems that the example program is using the global installation which usually doesn't happen unless you set the `NODE_PATH` env var.
