### ISSUE TITLE
Error: 'Browser.setWindowBounds' wasn't found

### ISSUE THREAD

**Issue by abacaj** [cyrus-and/chrome-remote-interface#131]
Using chrome latest (unstable). What is even more strange is when I call console.log(Browser) I see it defined but cannot use it.

**Comment by abacaj** [comment]
Full Stack:
```
{ Error: 'Browser.setWindowBounds' wasn't found
    at ProtocolError (/Users/anton/personal/node-selenium-starter/node_modules/chrome-remote-interface/lib/chrome.js:14:9)
    at /Users/anton/personal/node-selenium-starter/node_modules/chrome-remote-interface/lib/chrome.js:69:28
    at Chrome.handleMessage (/Users/anton/personal/node-selenium-starter/node_modules/chrome-remote-interface/lib/chrome.js:247:13)
    at WebSocket.<anonymous> (/Users/anton/personal/node-selenium-starter/node_modules/chrome-remote-interface/lib/chrome.js:224:27)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver._receiver.onmessage (/Users/anton/personal/node-selenium-starter/node_modules/ws/lib/WebSocket.js:143:54)
    at Receiver.dataMessage (/Users/anton/personal/node-selenium-starter/node_modules/ws/lib/Receiver.js:385:14)
    at extension.decompress (/Users/anton/personal/node-selenium-starter/node_modules/ws/lib/Receiver.js:354:40)
    at _inflate.flush (/Users/anton/personal/node-selenium-starter/node_modules/ws/lib/PerMessageDeflate.js:279:12) code: -32601 }
```

**Comment by cyrus-and** [comment]
Yeah, that's strange actually, it seems that the method is present in the protocol descriptor (even with the `remote` option) but it's not actually implemented.

You should file an issue to the [Chromium project] or to the [devtools-protocol]. Feel free to link to this issue if you do so.

> when I call console.log(Browser) I see it defined but cannot use it

This is just FYI, please note that the version you're seeing there (unless you're passing the `remote` option) is the local version of the `protocol.json` which may or may not be in sync with the version of Chrome you're using. More info [here][1] and [here][2].

[Chromium project]: https://bugs.chromium.org/p/chromium/issues/list
[devtools-protocol]: https://github.com/ChromeDevTools/devtools-protocol
[1]: https://github.com/cyrus-and/chrome-remote-interface#chrome-debugging-protocol-versions
[2]: https://github.com/cyrus-and/chrome-remote-interface/issues/129

**Comment by cyrus-and** [comment]
I'm closing this as there's nothing I can do about it, but if you decide to open an upstream issue please post the link here. Thanks!
