### ISSUE TITLE
Parse error with webpack at target(node)

### ISSUE THREAD

**Issue by mesutyigit** [cyrus-and/chrome-remote-interface#154]
```
ERROR in ./~/chrome-remote-interface/lib/protocol.json
Module parse failed: /Users/staj/hivecdn-new/hivecdnjs.chrome.remote.debug/node_modules/chrome-remote-interface/lib/protocol.json Unexpected token (2:13)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:13)
    at Parser.pp$4.raise (/Users/staj/hivecdn-new/hivecdnjs.chrome.remote.debug/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/staj/hivecdn-new/hivecdnjs.chrome.remote.debug/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/staj/hivecdn-new/hivecdnjs.chrome.remote.debug/node_modules/webpack/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/staj/hivecdn-new/hivecdnjs.chrome.remote.debug/node_modules/webpack/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/staj/hivecdn-new/hivecdnjs.chrome.remote.debug/node_modules/webpack/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Users/staj/hivecdn-new/hivecdnjs.chrome.remote.debug/node_modules/webpack/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Users/staj/hivecdn-new/hivecdnjs.chrome.remote.debug/node_modules/webpack/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Users/staj/hivecdn-new/hivecdnjs.chrome.remote.debug/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/staj/hivecdn-new/hivecdnjs.chrome.remote.debug/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/staj/hivecdn-new/hivecdnjs.chrome.remote.debug/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
    at Parser.parse (/Users/staj/hivecdn-new/hivecdnjs.chrome.remote.debug/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/Users/staj/hivecdn-new/hivecdnjs.chrome.remote.debug/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/Users/staj/hivecdn-new/hivecdnjs.chrome.remote.debug/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/Users/staj/hivecdn-new/hivecdnjs.chrome.remote.debug/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /Users/staj/hivecdn-new/hivecdnjs.chrome.remote.debug/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/staj/hivecdn-new/hivecdnjs.chrome.remote.debug/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/staj/hivecdn-new/hivecdnjs.chrome.remote.debug/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)
 @ ./~/chrome-remote-interface/lib/devtools.js 13:32-58
```

**Comment by cyrus-and** [comment]
Could you please explain what you're trying to achieve and the command that caused the above error...?

**Comment by cyrus-and** [comment]
Bump.
