### ISSUE TITLE
URL in separate context gives invalid URL

### ISSUE THREAD

**Issue by tim-field** [cyrus-and/chrome-remote-interface#181]
Running this example 

https://github.com/cyrus-and/chrome-remote-interface/wiki/Load-a-URL-in-a-separate-context-(headless-mode-only)

Gives

```
(node:756) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: invalid url
(node:756) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```
google-chrome --version
Google Chrome 59.0.3071.115
node -v
v7.9.0
```

Starting with
`google-chrome --headless --remote-debugging-port=9222 --disable-gpu`

**Comment by cyrus-and** [comment]
Same Chrome version here. Try again with `node --trace-warnings` and paste the full stack trace.

**Comment by tim-field** [comment]
```
node --trace-warnings tabs.js 
(node:22639) Error: invalid url
    at WebSocket.initAsClient (/srv/www/urlToPdf/node_modules/ws/lib/WebSocket.js:540:47)
    at new WebSocket (/srv/www/urlToPdf/node_modules/ws/lib/WebSocket.js:70:20)
    at /srv/www/urlToPdf/node_modules/chrome-remote-interface/lib/chrome.js:202:26
    at Chrome.connectToWebSocket (/srv/www/urlToPdf/node_modules/chrome-remote-interface/lib/chrome.js:196:12)
    at /srv/www/urlToPdf/node_modules/chrome-remote-interface/lib/chrome.js:113:35
(node:22639) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:69:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:86:11)
    at runMicrotasksCallback (internal/process/next_tick.js:67:9)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by cyrus-and** [comment]
Thanks, it looks like you're using an old version, that wiki requires version 0.23.0 at least. Please upgrade to the latest version.
