### ISSUE TITLE
Error: Object reference chain is too long

### ISSUE THREAD

**Issue by dpnishant** [cyrus-and/chrome-remote-interface#201]
When I put the following snippet in the debugger.paused event handler, I get the error (mentioned below the snippet) for some values of the `elements` array (refer the snippet). How can I debug this further?

## Snippet
```js
var elements = ['a', 'b.c', '_qq'];

var Promises = [];

for (var i = 0; i < elements.length; i++) {
    Promises.push(Runtime.evaluate({
        expression: elements[i].toString(),
        returnByValue: true
    }));
}

Promise.all(Promises).then(function(output) {
    for (var i = 0; i < output.length; i++) {
        console.log('\t' + elements[i] + " = " + JSON.stringify(output[i].result.value));
    }
}).catch(function(error) {
    console.log("[E]", error.stack);
});
```

## Error
```sh
Error: Object reference chain is too long
    at /Users/dpnishant/node_modules/chrome-remote-interface/lib/chrome.js:81:28
    at Chrome.handleMessage (/Users/dpnishant/node_modules/chrome-remote-interface/lib/chrome.js:271:13)
    at WebSocket.<anonymous> (/Users/dpnishant/node_modules/chrome-remote-interface/lib/chrome.js:248:27)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:194:7)
    at Receiver._receiver.onmessage (/Users/dpnishant/node_modules/chrome-remote-interface/node_modules/ws/lib/WebSocket.js:143:54)
    at Receiver.dataMessage (/Users/dpnishant/node_modules/chrome-remote-interface/node_modules/ws/lib/Receiver.js:385:14)
    at extension.decompress (/Users/dpnishant/node_modules/chrome-remote-interface/node_modules/ws/lib/Receiver.js:354:40)
    at _inflate.flush (/Users/dpnishant/node_modules/chrome-remote-interface/node_modules/ws/lib/PerMessageDeflate.js:279:12)
    at afterWrite (_stream_writable.js:383:3)
    at onwrite (_stream_writable.js:374:7)
```

**Comment by cyrus-and** [comment]
Are `'a'`, `'b.c'` and `'_qq'` HTML element ids? I don't think you can fetch a whole DOM JavaScript from Node.js and `returnByValue` is documented as:

> Whether the result is expected to be a JSON object which should be sent by value.

AFAIK the proper way to interact with DOM objects is to fetch it normally, for example:

```js
>>> Runtime.evaluate({expression: 'document'})
{ result: 
   { result: 
      { type: 'object',
        subtype: 'node',
        className: 'HTMLDocument',
        description: '#document',
        objectId: '{"injectedScriptId":1,"id":6}' } } }
```

Then use `objectId` , for example, with [`Runtime.getProperties`][1] or [`Runtime.callFunctionOn`][2] to interact. Or more easily just use `Runtime.evaluate` to accomplish the same.

What are you trying to achieve?

[1]: https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-getProperties
[2]: https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-callFunctionOn

**Comment by dpnishant** [comment]
@cyrus-and Yes indeed they belong to the HTMLElement class. I was trying to read the values of certain identifiers when a particular breakpoint hits. Proper error handling has solved it for me.

Thanks a lot for the pointers.
