### ISSUE TITLE
ECONNREFUSED error

### ISSUE THREAD

**Issue by sonyarianto** [cyrus-and/chrome-remote-interface#211]
I run this code

```js
const CDP = require('chrome-remote-interface');

async function example() {
    try {
        // connect to endpoint
        var client = await CDP();
        // extract domains
        const {Network, Page} = client;
        // setup handlers
        Network.requestWillBeSent((params) => {
            console.log(params.request.url);
        });
        // enable events then start!
        await Promise.all([Network.enable(), Page.enable()]);
        await Page.navigate({url: 'https://github.com'});
        await Page.loadEventFired();
    } catch (err) {
        console.error(err);
    } finally {
        if (client) {
            await client.close();
        }
    }
}

example();
```

But I always get this error.

```
{ Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object.exports._errnoException (util.js:1024:11)
    at exports._exceptionWithHostPort (util.js:1047:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }
```

Any help are appreciated.

**Comment by cyrus-and** [comment]
Is Chrome running and using the `--remote-debugging-port=9222` option?

What if you manually try to navigate to http://localhost:9222/json/list ?

**Comment by sonyarianto** [comment]
Ow I think chrome is not running. Sorry and thanks. I thought it will automatically launch Chrome?

**Comment by cyrus-and** [comment]
Nope you have to start it manually or use a third party module if you want to do it programmatically, for example [chrome-launcher][1].

[1]: https://www.npmjs.com/package/chrome-launcher
