### ISSUE TITLE
WebSocket Error: not opened

### ISSUE THREAD

**Issue by hgfdd** [cyrus-and/chrome-remote-interface#221]
When `Page.navigate` overlimit the time, the following timeout happens:

```js
            setTimeout(function() {
                if (page_loaded == true) 
		{
                    return;
                }
		page_load_failed = true;
                console.log('Timeout: trying to check the state...');

		/*setTimeout(function() {
                            closeTarget(CDP, true, client);
                        }, 15000);*/

                Runtime.evaluate({
                    expression: 'document.readyState'
                }).then((result, err) => {
                    console.log(result);
                    console.log(err);
                    if (result.result.value == 'interactive' || result.result.value == 'complete') {
                        console.log('document state is interactive...');
                        pageLoaded();

                    } else {
                        console.log('Can\'t load the page...');
                        closeTarget(CDP, false, client);
                    }
                }).catch((err) => {
                    console.log('Can\'t load the page...');
		    console.log('>>>>>>>>>>>>>>', exit_done);
                    console.error(err);
                    //closeTarget(CDP, false);
		    CDP.List(options, function (err, targets) {
    		    if (!err) 
			{
        			//console.log(targets);
				var str = JSON.stringify(targets);
				console.log(targetValueToCheck);
				if (str.includes(targetValueToCheck))
				{
					console.log('Target already exists...');
					//checkDocumentState();
					closeTarget(CDP, false,client);					
				}
				else
				{
					//main();
					console.log('No such target...');
					closeTarget(CDP, false, client);
				}
    			} else { console.log(err); }
		    });
                });

            }, page_timeout);
```

And sometimes in `Runtime.evaluate` happens this error:
```
Error: not opened
    at WebSocket.send (/opt/forsys/rss/node_modules/chrome-remote-interface/node_modules/ws/lib/WebSocket.js:355:18)
    at Chrome.enqueueCommand (/opt/forsys/rss/node_modules/chrome-remote-interface/lib/chrome.js:124:16)
    at /opt/forsys/rss/node_modules/chrome-remote-interface/lib/chrome.js:86:28
    at Chrome.send (/opt/forsys/rss/node_modules/chrome-remote-interface/lib/chrome.js:85:16)
    at Object.handler [as evaluate] (/opt/forsys/rss/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at Timeout._onTimeout (/opt/forsys/rss/url_readability.js:351:25)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

`clint.close()` was't executed before and the target exists. What can go wrong?

Hope on your responce!

**Comment by cyrus-and** [comment]
It happens when you try to send a command through a closed WebSocket connection, it can happen either if `client.close()` is called (which apparently is not your case) or if the tab is closed.

Maybe you fail to clear that timeout in case of a successful page load?

**Comment by hgfdd** [comment]
> Maybe you fail to clear that timeout in case of a successful page load?

What do you mean? I

I have remade this by domEventFired, but also after timeout `Runtime.evaluate` do not work and i get the same error.

This is current code:
```
 CDP(targetOptions, (client) => {
        // Extract used DevTools domains.

        console.log('Extract used DevTools domains');
        const {
            Page,
            Network,
            Runtime,
            DOM,
            Security
        } = client;

        // Enable events on domains we are interested in.
        Promise.all([
            Page.enable(),
            Runtime.enable(),
            DOM.enable(),
            Security.enable(),
            Network.enable()
        ]).then(() => {

            setTimeout(function() {
		if (domLoaded == true)
		{
			console.log('document state is interactive...');
			pageLoaded();
		}
		else
		{
			console.log('Can\'t load the page!');
			closeTarget(CDP, false, client);
		}
            }, page_timeout);

            Network.setBlockedURLs({
                urls: blackListURLs
            });

            return Page.navigate({
                url: downloaded_url
            }).then((res) => {
                console.log(res);
            });

        }).catch((err) => {
            console.error(err);
            closeTarget(CDP, false, client);
        });

        function pageLoaded() {

            var script = fs.readFileSync(readability_js, 'utf8');

            var saveOutTitlePromise = saveOutTitle(Runtime);
            var saveOrigPromise = saveOrigHtml(DOM, Runtime);
            var jsRulesPromise = applyJsRules(Runtime);
            var jQueryPromise = testJQuery(Page, Runtime);

            Promise.all([saveOutTitlePromise, saveOrigPromise, jsRulesPromise, jQueryPromise]).then(values => {
                console.log('Executing clearly/readability...');
                Runtime.evaluate({
                    expression: script
                }).then((result) => {
                    console.log('Clearly/readability executed...');
                    Runtime.evaluate({
                        expression: 'document.documentElement.innerHTML = clearly()'
                    }).then((result) => {
                        //console.log(result);
                        if (result["result"]["subtype"] == 'error') {
                            console.log('clearly() failed...');
                            closeTarget(CDP, false, client);
                        }
                        Runtime.evaluate({
                            expression: 'document.documentElement.innerHTML'
                        }).then((result) => {
                            console.log(do_save_png);
                            if (do_save_png) {
                                captureScreenShot(Page);
                            }

                            var plainTextPromise = getPlainText(Runtime);

                            var fs = require('fs');
                            fs.writeFileSync(out, result.result.value, {
                                mode: '666'
                            });
                            console.log("The file was saved!");

                            Promise.all([plainTextPromise]).then(() => {
                                console.log('Client closed!');
                                closeTarget(CDP, true, client);
                            });
                        });
                    }).catch((err) => {
			    console.error(err);
			    console.log('Terminating...');
			    closeTarget(CDP, false, client);
			});
                }).catch((err) => {
			    console.error(err);
			    console.log('Terminating...');
			    closeTarget(CDP, false, client);
			});
            }).catch((error) => {
		  console.log(error);
		  console.log('Terminating...');
		  closeTarget(CDP, false, client);
		  //done();
		});
        }

        // Evaluate outerHTML after page has loaded.
        Page.loadEventFired(() => {
            console.log('Page loaded...');
            pageLoaded();
        });

        Page.domContentEventFired(() => {
            console.log('dom loaded...');
            domLoaded = true;
        });

    }).on('error', (err) => {
        console.error('Cannot connect to browser:', err);
        process.exit(1);
    });
```

**Comment by cyrus-and** [comment]
> What do you mean?

If you use a timeout to catch page unresponsiveness you should cancel it once the `Page.loadEventFired` event fires, otherwise the timeout function executes anyway possibly after the code that handles the correct page load, thus running `pageLoaded` again and hence attempting to send methods on a closed WebSocket. I mean something like this:

```js
const id = setTimeout(() => /*...*/);

Page.loadEventFired(() => {
    clearTimeout(id);
    /*...*/
});

```

---

P.S. you should really use `async`/`await` to deal with promises if your environment allows it.

**Comment by hgfdd** [comment]
> If you use a timeout to catch page unresponsiveness you should cancel it once the 
> Page.loadEventFired event fires, otherwise the timeout function executes anyway possibly after the 
> code that handles the correct page load, thus running pageLoaded again and hence attempting to 
> send methods on a closed WebSocket. I mean something like this:

It didn't help

**Comment by hgfdd** [comment]
When timeout is fired, somehow websocket is closed.

**Comment by cyrus-and** [comment]
The point is that the timeout should fire only if `Page.loadEventFired` doesn't. In any case the error itself is pretty straightforward to understand: activity performed on a closed connection. So you just have to make sure that this cannot happen and double check your program flow.

I'd like to help you further with this but I cannot run your code, if you manage to provide a standalone snippet that identify your issue, I'd be happy to look into it.

**Comment by hgfdd** [comment]
> The point is that the timeout should fire only if Page.loadEventFired doesn't. In any case the error 
> itself is pretty straightforward to understand: activity performed on a closed connection. So you just 
> have to make sure that this cannot happen and double check your program flow.

It was very useful advice. Thanks!

But now, rarely, i'm getting the following error:

```
Cannot connect to browser: Error: unexpected server response (500)
    at ClientRequest._req.on (/opt/forsys/rss/node_modules/chrome-remote-interface/node_modules/ws/lib/WebSocket.js:651:26)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at Socket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
```

It happens when this code is executed: (in `CDP(targetOptions, (client) => {`)
```
function loadPage(mode) {
        CDP(targetOptions, (client) => {
.....
}

function main() {
    CDP.New(options, function(err, target) {
        if (err) {
            console.log('ERROR: target is not openning!');
            console.log(err);
            process.exit(1);
        }
        console.log('Target openned...');
        createdTarget = target;
        targetValueToCheck = target['id'];

        targetOptions = {
            host: arg_host,
            port: chrome_port,
            id: target.id
        };

        loadPage(1);
    });
}

main();
```

What can go wrong?

**Comment by cyrus-and** [comment]
I can't see anything wrong with that code except that the `id` field is not used by CDP, do you mean `targetOptions = {/*...*/, target: target.id}`?

What version of chrome-remote-interface are you using?

(Please next time fill the issue template.)

**Comment by dr-dimitru** [comment]
#### TL;TR;

This is caused by `--use-fake-device-for-media-stream` flag, removing it will fix this issue for some edge cases.

#### Full story:
We've run into the same issue, *struggled for 3 days*, at the end we found out this was caused by `--use-fake-device-for-media-stream` flag of `chrome` process.

This was happening only for some pages, *perhaps those where media stream devices are checked*.

Exact Exception:
```
"Uncaught (in promise) NetworkError: A network error occurred.", source: https://example.com
```

Exact error of `Runtime.evaluate({/*..*/}).catch()`:
```
Error: not opened
```
