### ISSUE TITLE
Cannot evaluate page

### ISSUE THREAD

**Issue by mato75** [cyrus-and/chrome-remote-interface#23]
When page is ready, I do Page.navigate({ url: new-url }) and then I try to evaluate code, but unfortunately I get an error:

````
/nwjs-ui-testing/node_modules/chrome-remote-interface/node_modules/ws/lib/WebSocket.js:219
    else throw new Error('not opened');
               ^
Error: not opened
    at WebSocket.send (/nwjs-ui-testing/node_modules/chrome-remote-interface/node_modules/ws/lib/WebSocket.js:219:16)
    at Chrome.send (/nwjs-ui-testing/node_modules/chrome-remote-interface/lib/chrome.js:199:13)
    at Object.self.(anonymous function).(anonymous function) [as evaluate] (/nwjs-ui-testing/node_modules/chrome-remote-interface/lib/chrome.js:227:14)
    at evalFindPos (/wjs-ui-testing/test.js:56:16)
    at nextTask (/nwjs-ui-testing/node_modules/async/dist/async.js:3921:18)
    at Object.waterfall (/nwjs-ui-testing/node_modules/async/dist/async.js:3924:9)
    at getElementPosition (/nwjs-ui-testing/test.js:52:8)
    at null.<anonymous> (/nwjs-ui-testing/test.js:32:26)
    at wrapper [as _onTimeout] (timers.js:265:14)
    at Timer.listOnTimeout `(timers.js:110:15)

````

Browser and page are opened, what could be the reason for this issue?

**Comment by cyrus-and** [comment]
That "not opened" refers to the WebSocket, it may happen if you send commands after that you call [close()][1]. If that's not the case, can you please provide me some minimal code snippet that reproduces the issue?

[1]: https://github.com/cyrus-and/chrome-remote-interface#chromeclose

**Comment by cyrus-and** [comment]
Did you get any further with this?
