### ISSUE TITLE
Page.screencastFrameAck expects an integer

### ISSUE THREAD

**Issue by positlabs** [cyrus-and/chrome-remote-interface#241]
I've found a bug with the `Page.screencastFrameAck` method. It is borking, saying it expects an integer. I have checked the type of the value I'm passing back, and it's a `number`. I'm grabbing the `sessionId` directly from the `Page.screencastFrame` event payload, so I'm confused about why it thinks it's incorrect.

```js
let target = await CDP.New({url})
let client = await CDP({target})
await client.Page.enable()

client.on('Page.screencastFrame', (frame) => {
	console.log('Page.screencastFrame', frame.sessionId, typeof frame.sessionId)
	client.Page.screencastFrameAck(frame.sessionId)
})
	
// https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-startScreencast
client.Page.startScreencast()
```

```
0|usaa-fly | Page.screencastFrame 1 number
0|usaa-fly | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|usaa-fly | Error: Invalid parameters (sessionId: integer value expected)
0|usaa-fly |     at /app/node_modules/chrome-remote-interface/lib/chrome.js:90:30
0|usaa-fly |     at Chrome.handleMessage (/app/node_modules/chrome-remote-interface/lib/chrome.js:289:13)
0|usaa-fly |     at WebSocket.<anonymous> (/app/node_modules/chrome-remote-interface/lib/chrome.js:266:27)
0|usaa-fly |     at emitTwo (events.js:125:13)
0|usaa-fly |     at WebSocket.emit (events.js:213:7)
0|usaa-fly |     at Receiver._receiver.onmessage (/app/node_modules/ws/lib/WebSocket.js:143:54)
0|usaa-fly |     at Receiver.dataMessage (/app/node_modules/ws/lib/Receiver.js:385:14)
0|usaa-fly |     at extension.decompress (/app/node_modules/ws/lib/Receiver.js:354:40)
0|usaa-fly |     at _inflate.flush (/app/node_modules/ws/lib/PerMessageDeflate.js:279:12)
0|usaa-fly |     at afterWrite (_stream_writable.js:452:3)
```

| Component | Version
|-|-
| Operating system	  	 	| linux
| Node.js					| 8.4.0
| Chrome/Chromium/...		| chrome stable
| chrome-remote-interface	| 0.24.3

Is Chrome running in a container? YES

**Comment by cyrus-and** [comment]
Methods always expect an object (i.e., not positional arguments):

```js
client.Page.screencastFrameAck({sessionId: frame.sessionId});
```

**Comment by positlabs** [comment]
Ah, got it! Thanks!
