### ISSUE TITLE
Possible reasons for "Script not found"?

### ISSUE THREAD

**Issue by dpnishant** [cyrus-and/chrome-remote-interface#243]
| Component | Version
|-|-
| Operating system	  	 	| macOS Sierra 10.12.6
| Node.js					| v8.2.1
| Chrome/Chromium/...		| Chrome Canary
| chrome-remote-interface	| 0.24.4

Is Chrome running in a container? NO

**Problem** 
I'm getting a strange error (strange because in the error stack I do not see any reference to any line-number of my code) like the following. Any pointers would be helpful.

```js
{ Error: Script not found
    at /Users/dpnishant/node_modules/chrome-remote-interface/lib/chrome.js:90:30
    at Chrome.handleMessage (/Users/dpnishant/node_modules/chrome-remote-interface/lib/chrome.js:289:13)
    at WebSocket.<anonymous> (/Users/dpnishant/node_modules/chrome-remote-interface/lib/chrome.js:266:27)
    at emitTwo (events.js:125:13)
    at WebSocket.emit (events.js:213:7)
    at Receiver._receiver.onmessage (/Users/dpnishant/node_modules/chrome-remote-interface/node_modules/ws/lib/WebSocket.js:143:54)
    at Receiver.dataMessage (/Users/dpnishant/node_modules/chrome-remote-interface/node_modules/ws/lib/Receiver.js:385:14)
    at extension.decompress (/Users/dpnishant/node_modules/chrome-remote-interface/node_modules/ws/lib/Receiver.js:354:40)
    at _inflate.flush (/Users/dpnishant/node_modules/chrome-remote-interface/node_modules/ws/lib/PerMessageDeflate.js:279:12)
    at afterWrite (_stream_writable.js:438:3)
    at onwrite (_stream_writable.js:429:7) response: { code: -32000, message: 'Script not found' } }
```

My code looks like as shown below:

```js
Debugger.scriptParsed(function (params) {
    Debugger.getPossibleBreakpoints({
        start: {
            scriptId: scriptId,
            lineNumber: 0,
            columnNumber: 0
        }
    }).then(function (possible) {
        for (let i = 0, j = possible.locations.length - 1; i <= j; i++) {
            Debugger.setBreakpointByUrl({
                lineNumber: possible.locations[i].lineNumber,
                columnNumber: possible.locations[i].columnNumber,
                url: params.scriptId
            }).then(function (_ref) {
                // do something here...
            }).catch(function (err1) {
                console.error(err1);
            });
        }
    }).catch(function (err2) {
        console.error(err2);
    });
});
```

**Comment by cyrus-and** [comment]
> strange because in the error stack I do not see any reference to any line-number of my code

Unfortunately this is the expected behavior since the error is originated from [this][1] rejection. I don't know if there are any workaround.

Well it looks like `scriptId: scriptId,` contains a wrong value, what's that? Possibly a typo but that code should be like:

```js
Debugger.scriptParsed(function ({scriptId}) {
    Debugger.getPossibleBreakpoints({
        start: {
            scriptId,
            lineNumber: 0,
            columnNumber: 0
        }
    })
    // ...
});
```

[1]: https://github.com/cyrus-and/chrome-remote-interface/blob/6e752a0c39950d4e90ebf3211622c520a3c8dcef/lib/chrome.js#L88-L90

**Comment by dpnishant** [comment]
@cyrus-and Yes, my bad. It was a typo. However that error is not consistent. I don't get it every time even for the exact same script on the exact same Page URL.

Since there is no more information on this issue to debug. We can close this issue and may be reopen when I can get more info.

Thanks for the help though!
