### ISSUE TITLE
Unable to take multiple screen captures (printToPDF) at the same time

### ISSUE THREAD

**Issue by bliu23** [cyrus-and/chrome-remote-interface#246]
I'm working on an application that allows users to download a screenshot of a website. The download button triggers headless chrome to launch, run some page logic, and eventually take a screenshot.

I'm running into an issue in which the user tries to download screenshots (asynchronous) at the same time. Two browsers are launched, run the page logic, and end up trying to take a screenshot at about the same time.

`'Error: Execution context was destroyed. at /<filepath>/node_modules/chrome-remote-interface/lib/chrome.js:90:30`

`Error: The previous printing job hasn't finished. at /<filepath>/node_modules/chrome-remote-interface/lib/chrome.js:90:30`

If there's ample time between the downloads, then there's no issue. 

For reference there's a similar issue here about queueing screenshots and then running them in succession, but in this case there's no pre-set jobs that will be run so I don't think it's a valid solution, especially since these downloads are run in different instances of headless chrome. (https://github.com/cyrus-and/chrome-remote-interface/issues/92)

Here's a simple example to replicate:
```js
var chromeRemoteInterface = require('chrome-remote-interface');
var chromeLauncher = require('chrome-launcher');

chromeLauncher.launch({
	port: 9222,
	chromeFlags: [
		'--disable-gpu',
		'--headless'
	]
})
	.then(function(chrome) {
		return chromeRemoteInterface()
			.then(function(client) {
				return Promise.all([client.Page.enable(), client.Runtime.enable(), client.Network.enable()])
					.then(function(){
						return client.Page.navigate({url: 'https://github.com/login'});
					})
					.then(function() {
						return client.Page.loadEventFired();
					})
					.then(function() {
						client.Page.printToPDF({
							printBackground: true,
						})
					})
					.then(function() {
						return chrome.kill();
					})
			})
	})
```

Open up two terminals and run these at the same time and you can see the error.

| Operating system	  	| MAC OSX
| Node.js					| 6.11.0
| Chrome/Chromium/...		| v60 Chrome Canary
| chrome-remote-interface	| 0.24.2

Is Chrome running in a container? NO

**Comment by bliu23** [comment]
I actually just understood the debugging port and options to use CRI/Chrome launcher incorrectly. I just wasn't passing in the correct port flags, which defaulted all CRI to port 9222 which caused this conflict.
