### ISSUE TITLE
DOM.describeNode not implemented

### ISSUE THREAD

**Issue by molant** [cyrus-and/chrome-remote-interface#255]
| Component | Version
|-|-
| Operating system	  	 	| Windows 10
| Node.js					| 8.4
| Chrome/Chromium/...		|  60.0.3112.113
| chrome-remote-interface	| 0.24.5

Is Chrome running in a container? NO

Issue:

[`DOM.describeNode`](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-describeNode) doesn't seem to be implemented in `chrome-remote-interface`.

![image](https://user-images.githubusercontent.com/606594/29990635-582d6390-8f31-11e7-9a94-bd951ed0784f.png)

**Comment by cyrus-and** [comment]
See [this][1] FAQ entry.

[1]: https://github.com/cyrus-and/chrome-remote-interface#invoking-domainmethod-i-obtain-domainmethod-is-not-a-function

```
$ chrome-remote-interface inspect
>>> DOM.describeNode()
TypeError: DOM.describeNode is not a function
    at repl:1:5
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at REPLServer.defaultEval (repl.js:241:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
    at emitOne (events.js:115:13)
    at REPLServer.emit (events.js:210:7)
    at REPLServer.Interface._onLine (readline.js:278:10)
    at REPLServer.Interface._line (readline.js:625:8)
```
```
$ chrome-remote-interface inspect --remote
>>> DOM.describeNode()
{ error:
   { code: -32000,
     message: 'Either nodeId, backendNodeId or objectId must be specified' } }
```

But note that `DOM.describeNode` requires Chrome version 62.

**Comment by molant** [comment]
Thanks!
