### ISSUE TITLE
Cannot capture screenshot, Chrome 61

### ISSUE THREAD

**Issue by GrigoriyDidorenko** [cyrus-and/chrome-remote-interface#262]
Cannot capture a screenshot, since Chrome 61 released. Both on stable Chrome 61.0.3163.79 and beta Chrome 61.0.3163.71 on Ubuntu.  My code for taking screen below:

```
const screenshot = await Page.captureScreenshot({
                format,
                fromSurface: true,
                quality: 1,
                clip: {
                    width: 1440,
                    height: 900
                }
            });
```

With such params, I am getting the following exception.
```
 Exception while taking screenshot: { Error: Invalid parameters
    at D:\video_capturer\chromeNode\node_modules\chrome-remote-interface\lib\chrome.js:81:28
    at Chrome.handleMessage (D:\video_capturer\chromeNode\node_modules\chrome-remote-interface\lib\chrome.js:271:13)
    at WebSocket.<anonymous> (D:\video_capturer\chromeNode\node_modules\chrome-remote-interface\lib\chrome.js:248:27)
    at emitTwo (events.js:125:13)
    at WebSocket.emit (events.js:213:7)
    at Receiver._receiver.onmessage (D:\video_capturer\chromeNode\node_modules\ws\lib\WebSocket.js:143:54)
    at Receiver.dataMessage (D:\video_capturer\chromeNode\node_modules\ws\lib\Receiver.js:385:14)
    at extension.decompress (D:\video_capturer\chromeNode\node_modules\ws\lib\Receiver.js:354:40)
    at _inflate.flush (D:\video_capturer\chromeNode\node_modules\ws\lib\PerMessageDeflate.js:279:12)
    at afterWrite (_stream_writable.js:452:3)
  code: -32602,
  data: 'clip.x: double value expected; clip.y: double value expected'
```

OK, I've tried to add these new non-optional params

```
const screenshot = await Page.captureScreenshot({
                format,
                fromSurface: true,
                quality: 1,
                clip: {
                    width: 1440,
                    height: 900,
                    x: 100,
                    y: 0,
                    scale: 1
                }
            });
```

Now It's just freezing without any logging.

**Comment by wordcount** [comment]
the same issue here

**Comment by cyrus-and** [comment]
@wordcount then open a new issue with a minimal example so I can try to reproduce the problem.

**Comment by wordcount** [comment]
> @wordcount then open a new issue with a minimal example so I can try to reproduce the problem.
solved, thx

**Comment by ajimix** [comment]
@wordcount how did you solve the problem? I have a script that has been running for several months taking screenshots and I started to get an issue recently where the captureScreenshot promise never resolves or throws any error for some websites.

**Comment by cyrus-and** [comment]
> then open a new issue with a minimal example so I can try to reproduce the problem.

@ajimix same thing applies to you too! :)
