### ISSUE TITLE
Unknown command: protocol

### ISSUE THREAD

**Issue by rennomarcus** [cyrus-and/chrome-remote-interface#293]
| Component | Version
|-|-
| Operating system	  	 	| Ubuntu 14.04
| Node.js					| 8.0.0 and 9.0.0
| Chrome/Chromium/...		| Version 59.0.3071.115 (Official Build) (64-bit)
| chrome-remote-interface	| 0.25.2

Is Chrome running in a container? Desktop | Headless

I'm running in one tab `google-chrome --headless --remote-debugging-port=9222`
On the other tab I try to run one project that has as dependency this project. I'm also trying to run the [example](https://github.com/cyrus-and/chrome-remote-interface#sample-api-usage) from README.md

Both of them give me this error:
```
Unknown command: protocol
Error: Unknown command: protocol
    at IncomingMessage.<anonymous> (/home/mvr/workspace/frontend/node_modules/chrome-remote-interface/lib/external-request.js:18:26)
    at emitNone (events.js:120:20)
    at IncomingMessage.emit (events.js:218:7)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

If I visit `http://127.0.0.1:9222/json` on firefox I can see the json file. Any help would be appreciated. I checked that file, external-request.js, but I couldn't see anything strange.

**Comment by rennomarcus** [comment]
Wow.... I had to run `chromium-browser` rather than `google-chrome`! Awesome!
