### ISSUE TITLE
Related Issue Discovered via Chromeless

### ISSUE THREAD

**Issue by export-mike** [cyrus-and/chrome-remote-interface#306]
I'm using chromeless and getting this underlying exception from chrome-remote-interface.

Basically I'm trying to interact with a text field but I get an exception: 

```
{ Error: Element is not focusable
    at /Users/mikejames/projects/company/myApp/node_modules/chrome-remote-interface/lib/chrome.js:90:30
    at Chrome.handleMessage (/Users/mikejames/projects/company/myApp/node_modules/chrome-remote-interface/lib/chrome.js:289:13)
    at WebSocket.<anonymous> (/Users/mikejames/projects/company/myApp/node_modules/chrome-remote-interface/lib/chrome.js:266:27)
    at emitTwo (events.js:125:13)
    at WebSocket.emit (events.js:213:7)
    at Receiver._receiver.onmessage (/Users/mikejames/projects/company/myApp/node_modules/ws/lib/WebSocket.js:143:54)
    at Receiver.dataMessage (/Users/mikejames/projects/company/myApp/node_modules/ws/lib/Receiver.js:385:14)
    at extension.decompress (/Users/mikejames/projects/company/myApp/node_modules/ws/lib/Receiver.js:354:40)
    at _inflate.flush (/Users/mikejames/projects/company/myApp/node_modules/ws/lib/PerMessageDeflate.js:279:12)
    at afterWrite (_stream_writable.js:438:3)
    at onwrite (_stream_writable.js:429:7)
  response: { code: -32000, message: 'Element is not focusable' } }
```

https://github.com/graphcool/chromeless/issues/338

| Component | Version
|-|-
| Operating system	  	 	| OSX 10.13.1
| Node.js					| 8.1.3
| Chrome/Chromium/...		| Chrome
| chrome-remote-interface	| 0.24.5

Is Chrome running in a container? NO

**Comment by cyrus-and** [comment]
Well, it means that for some reason Chrome cannot focus that element, is it enabled? The following snippet reproduces the error:

```js
const CDP = require('chrome-remote-interface');

CDP(async (client) => {
    const {Network, DOM, Page, Runtime} = client;
    try {
        await Page.enable();
        await Promise.all([
            Page.navigate({url: 'data:text/html,<input disabled id="foo" />'}),
            Page.loadEventFired()
        ]);
        const {root} = await DOM.getDocument();
        const {nodeId} = await DOM.querySelector({
            nodeId: root.nodeId,
            selector: '#foo'
        });
        await DOM.focus({nodeId});
    } catch (err) {
        console.error(err);
    } finally {
        client.close();
    }
}).on('error', (err) => {
    console.error(err);
});
```

**Comment by cyrus-and** [comment]
It should be pretty clear the reason if you know the app. Otherwise you can debug it using this module by printing all the attributes of the node instead of focusing it using [`DOM.getAttributes`][1] to check whether it is enabled or not. In the above case:

```
{ attributes: [ 'disabled', '', 'id', 'foo' ] }
```

Or simply use [`Runtime.method-evaluate`][2] to inject some JavaScript debug code.

[1]: https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-getAttributes
[2]: https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate

**Comment by cyrus-and** [comment]
If the element is not actually disabled you can start digging deeper from [here][1] to check other reasons.

[1]: https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/inspector/InspectorDOMAgent.cpp?l=1260&rcl=6f1c8d9e6c2b5f4d3760c5aab469c638494a175a

**Comment by export-mike** [comment]
Thanks @cyrus-and for your help 👍
