### ISSUE TITLE
Issue with the inspect command 

### ISSUE THREAD

**Issue by goelayu** [cyrus-and/chrome-remote-interface#318]
| Component | Version
|-|-
| Operating system	  	 	| ubuntu
| Node.js					| 4.2.6
| Chrome/Chromium/...		| 63.0.3239.84
| chrome-remote-interface	| 0.25.5

Is Chrome running in a container?  NO

While running the inspect command, nodejs gives me the following error:
```
ayushgoel@ubuntu:~/webProject/data$ chrome-remote-interface inspect                                                                      
>>> fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at loadHistory (/home/ayushgoel/.npm-global/lib/node_modules/chrome-remote-interface/bin/client.js:78:16)
    at EventEmitter.<anonymous> (/home/ayushgoel/.npm-global/lib/node_modules/chrome-remote-interface/bin/client.js:174:9)
    at EventEmitter.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at /home/ayushgoel/.npm-global/lib/node_modules/chrome-remote-interface/lib/chrome.js:164:30
    at nextTickCallbackWith0Args (node.js:419:9)
```

**Comment by cyrus-and** [comment]
Please provide the remaining version information of the issue template.

| Component | Version
|-|-
| Operating system	  	 	| WRITE HERE
| Node.js					| WRITE HERE
| Chrome/Chromium/...		| WRITE HERE
| chrome-remote-interface	| WRITE HERE

**Comment by goelayu** [comment]
@cyrus-and updated

**Comment by cyrus-and** [comment]
I think it's a bug in Node.js version 4:

```
$ node
> fs.readFileSync(1)
TypeError: path must be a string
    at TypeError (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at repl:1:4
    at REPLServer.defaultEval (repl.js:252:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:417:12)
    at emitOne (events.js:82:20)
    at REPLServer.emit (events.js:169:7)
```

Yet the [doc][1] says:

> file String | Integer filename or file descriptor

Update Node.js to fix this.

[1]: https://nodejs.org/dist/v4.2.6/docs/api/fs.html#fs_fs_readfile_file_options_callback

**Comment by goelayu** [comment]
Great. That worked!
