### ISSUE TITLE
Cannot cleanly close a client when you are intercepting Network requests

### ISSUE THREAD

**Issue by nddipiazza** [cyrus-and/chrome-remote-interface#347]
i have a chrome-remote-interface where I am intercepting requests. 

I will wait a timeout, say 10 seconds, then I will close the client. 

Upon closing the client, I will often get an exception thrown, such as:

```
(node:11698) UnhandledPromiseRejectionWarning: Error: not opened
    at WebSocket.send (/snapshot/chrome-remote-interface-js-eval/node_modules/ws/lib/WebSocket.js:359:18)
    at Chrome.enqueueCommand (/snapshot/chrome-remote-interface-js-eval/node_modules/chrome-remote-interface/lib/chrome.js:130:16)
    at Chrome.send (/snapshot/chrome-remote-interface-js-eval/node_modules/chrome-remote-interface/lib/chrome.js:88:28)
    at new Promise (<anonymous>)
    at Chrome.send (/snapshot/chrome-remote-interface-js-eval/node_modules/chrome-remote-interface/lib/chrome.js:87:16)
    at Object.handler [as continueInterceptedRequest] (/snapshot/chrome-remote-interface-js-eval/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at Chrome.Network.requestIntercepted (/snapshot/chrome-remote-interface-js-eval/cri-js-eval.js:0:0)
    at Chrome.emit (events.js:182:13)
    at Chrome.handleMessage (/snapshot/chrome-remote-interface-js-eval/node_modules/chrome-remote-interface/lib/chrome.js:311:16)
    at WebSocket.<anonymous> (/snapshot/chrome-remote-interface-js-eval/node_modules/chrome-remote-interface/lib/chrome.js:274:27)
(node:11698) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11698) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11698) UnhandledPromiseRejectionWarning: Error: not opened
    at WebSocket.send (/snapshot/chrome-remote-interface-js-eval/node_modules/ws/lib/WebSocket.js:359:18)
    at Chrome.enqueueCommand (/snapshot/chrome-remote-interface-js-eval/node_modules/chrome-remote-interface/lib/chrome.js:130:16)
    at Chrome.send (/snapshot/chrome-remote-interface-js-eval/node_modules/chrome-remote-interface/lib/chrome.js:88:28)
    at new Promise (<anonymous>)
    at Chrome.send (/snapshot/chrome-remote-interface-js-eval/node_modules/chrome-remote-interface/lib/chrome.js:87:16)
    at Object.handler [as continueInterceptedRequest] (/snapshot/chrome-remote-interface-js-eval/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at Chrome.Network.requestIntercepted (/snapshot/chrome-remote-interface-js-eval/cri-js-eval.js:0:0)
    at Chrome.emit (events.js:182:13)
    at Chrome.handleMessage (/snapshot/chrome-remote-interface-js-eval/node_modules/chrome-remote-interface/lib/chrome.js:311:16)
    at WebSocket.<anonymous> (/snapshot/chrome-remote-interface-js-eval/node_modules/chrome-remote-interface/lib/chrome.js:274:27)
```

This is because i closed the client while there was a request being still intercepted. 

How can I prevent this error? Is there a way to "turn off" network intercepts and then close my client?

**Comment by cyrus-and** [comment]
[This wiki][1] seems to work, even adding a 10s timeout. Can you please provide a minimal example, so I can try to reproduce the issue locally?

[1]: https://github.com/cyrus-and/chrome-remote-interface/wiki/Intercept-and-block-requests-by-URL

**Comment by nddipiazza** [comment]
Hi @cyrus-and 
can i just send you the whole nodejs program thru gmail or something? my gmail is `nicholas.dipiazza` if you drop me an email i will respond with the code. 

if not, i can try to extract it from the nodejs program

**Comment by nddipiazza** [comment]
got your email. I sent the script and steps.

**Comment by cyrus-and** [comment]
I took a look at your code. Basically it boils down to something like this:

```js
const CDP = require('chrome-remote-interface');

async function reproduce () {
    const client = await CDP();

    setTimeout(async () => {
        await client.Page.reload(); // Error: not opened
    }, 1000);

    await client.close();
}

reproduce();
```

That is, there is some *pending* code that is run after that the client closes the connection. In the above example this is simulated by using a timeout, in your case it's code that is executed inside an event handler:

1. event is fired and `method` is about to be called;
2. connection is closed;
3. `method` is called.

There's nothing to worry about, you can (and should, always...) handle the errors for all the methods that you call. In this case the example becomes:

```js
const CDP = require('chrome-remote-interface');

async function reproduce () {
    const client = await CDP();

    setTimeout(async () => {
        try {
            await client.Page.reload();
        } catch (err) {
            console.error("Whoops, the connection died in the meantime...");
        }
    }, 1000);

    await client.close();
}

reproduce();
```

Please let me know if you need some help in patching the original code.

**Comment by nddipiazza** [comment]
thanks @cyrus-and 
i like the idea of putting some try catches in my code to safely capture these harmless exceptions and log them in a debug level. will do.
