### ISSUE TITLE
Getting Error: connect ECONNREFUSED 127.0.0.1:9222 with Chrome 69

### ISSUE THREAD

**Issue by benzaremean** [cyrus-and/chrome-remote-interface#356]
| Component | Version
|-|-
| Operating system	  	 	| OS X High Sierra
| Node.js					| v8.11.3
| Chrome/Chromium/...		| Google Chrome 69.0.3497.92
| chrome-remote-interface	| 0.26.1

Is Chrome running in a container? NO

I am getting error Error: connect ECONNREFUSED 127.0.0.1:9222 with Chrome 69

This is reproducible with example from your README page

```
const CDP = require('chrome-remote-interface');

async function example() {
    let client;
    try {
        // connect to endpoint
        client = await CDP();
        // extract domains
        const {Network, Page} = client;
        // setup handlers
        Network.requestWillBeSent((params) => {
            console.log(params.request.url);
        });
        // enable events then start!
        await Network.enable();
        await Page.enable();
        await Page.navigate({url: 'https://github.com'});
        await Page.loadEventFired();
    } catch (err) {
        console.error(err);
    } finally {
        if (client) {
            await client.close();
        }
    }
}

example();
```

error returned is
```
{ Error: connect ECONNREFUSED 127.0.0.1:9222
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 9222 }
```

**Comment by cyrus-and** [comment]
Did you start Chrome like [this][1]:

    google-chrome --remote-debugging-port=9222

[1]:  https://github.com/cyrus-and/chrome-remote-interface#desktop

**Comment by benzaremean** [comment]
thanks it works with that. Is that a new change?

**Comment by cyrus-and** [comment]
AFAIK is there since day 0, the remote debugging feature is too dangerous to be be enabled by default.
