### ISSUE TITLE
throwing ws error after upgrading ws version

### ISSUE THREAD

**Issue by hbakhtiyor** [cyrus-and/chrome-remote-interface#372]
i use upstream master, and getting error after this commit https://github.com/cyrus-and/chrome-remote-interface/commit/4b8dcee765f5ae6232a2f289c1a8264fdb5dfb28

```
Error: Unexpected server response: 404
    at ClientRequest.req.on (/demor/node_modules/chrome-remote-interface/node_modules/ws/lib/websocket.js:535:5)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:546:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:432:20)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at TLSSocket.Readable.push (_stream_readable.js:219:10)
    at TLSWrap.onread (net.js:638:20)
```

**Comment by cyrus-and** [comment]
Doing what exactly...?

**Comment by hbakhtiyor** [comment]
during creating new tab, i think it throws for any samples

**Comment by cyrus-and** [comment]
I cannot reproduce this. Please try to come up with a minimal standalone example that cases this issue.

**Comment by hbakhtiyor** [comment]
for example, 

```js
const CDP = require('chrome-remote-interface');

async function navigateInANewTab(url) {
    const options = { host: 'host', port: 443, secure: true, useHostName: true, local: false };
    const tab = await CDP.New(options);
    const client = await CDP(Object.assign(options, {tab}));
    await CDP.Close(Object.assign(options, {id: tab.id}));
}

navigateInANewTab('https://github.com');

```

**Comment by cyrus-and** [comment]
Is it reproducible even without `secure` and `useHostName`?

**Comment by hbakhtiyor** [comment]
i can't reproduce it locally without these options

**Comment by hbakhtiyor** [comment]
sent message to your email

**Comment by cyrus-and** [comment]
Hi sorry for the late reply (and thanks for the email) so apparently this is either a bug in `ws` or your backend because even using `wscat` fails with 404:

    wscat -c wss://YOURBACKEND/devtools/page/3103E3E5955B472A4FDC9DCEE7AC817A

But as you say, the fact is that old versions of `ws` work... let me try to debug it.

**Comment by cyrus-and** [comment]
OK so the difference is in the port of the host header of the request:

- Response `HTTP/1.0 404 The page you're looking for doesn't exist.`, host header field in request:

        Host: YOURBACKEND:443

- Response `HTTP/1.1 101 WebSocket Protocol Handshake`, host header field in request:

        Host: YOURBACKEND

Also note the HTTP version. I suspect this is a bug in your backend, double check you configuration and let me know.

**Comment by paambaati** [comment]
As a heads up, most HTTP clients (curl, Chrome, Firefox, ruby, AsyncHttpClient for Scala, and recently request for Node) have started dropping the port suffix from the header. This is still RFC compliant.

This thread includes a few relevant links - https://github.com/request/request/issues/2894
