### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Niek** [cyrus-and/chrome-remote-interface#390]
| Component | Version
|-|-
| Operating system	  	 	| Ubuntu 18.10
| Node.js					| v10.15.2
| Chrome/Chromium/...		| Google Chrome 72.0.3626.121
| chrome-remote-interface	| 0.27.1

Is Chrome running in a container? No

This is a hard to reproduce issue, but I got a few times this error right after connecting to a Chrome instance:

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Protocol.devToolsInterface (node_modules/chrome-remote-interface/lib/devtools.js:59:33)
    at IncomingMessage.response.on (node_modules/chrome-remote-interface/lib/external-request.js:32:17)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

It might be an idea to add try/catch blocks around the ``JSON.parse()`` calls?

**Comment by cyrus-and** [comment]
> It might be an idea to add try/catch blocks around the `JSON.parse()` calls?

You can try to do that to debug this issue, in practice it should never happen. Let me know if you catch something.

**Comment by cyrus-and** [comment]
Closing for now, feel free to comment if you catch that error again.
