### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by klodoma** [cyrus-and/chrome-remote-interface#48]
Hi, 

I used this interface with success in a ubuntu based docker container. 
I've upgraded now the system to the latest docker version and I have this error... 
ReferenceError: Promise is not defined. See bellow

Not sure where to start... Or what is the cause of this. Any ideas?

```
root@b17e220955cf:/producer# node /scripts/capture-test.js 

/node_modules/chrome-remote-interface/lib/chrome.js:42
        return new Promise(function (fulfill, reject) {
                   ^
ReferenceError: Promise is not defined
    at Chrome.send (/node_modules/chrome-remote-interface/lib/chrome.js:42:20)
    at Object.handler [as enable] (/node_modules/chrome-remote-interface/lib/chrome.js:108:21)
    at EventEmitter.<anonymous> (/scripts/capture-test.js:9:17)
    at EventEmitter.emit (events.js:95:17)
    at WebSocket.<anonymous> (/node_modules/chrome-remote-interface/lib/chrome.js:251:23)
    at WebSocket.EventEmitter.emit (events.js:92:17)
    at WebSocket.establishConnection (/node_modules/chrome-remote-interface/node_modules/ws/lib/WebSocket.js:887:8)
    at ClientRequest.upgrade (/node_modules/chrome-remote-interface/node_modules/ws/lib/WebSocket.js:778:25)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:106:17)

```

capture-test.js - contains your sample API usage code. Copy pasted.

**Comment by cyrus-and** [comment]
Which version of Node.js are you using? You can find it out by running `node --version`.

Also try to run the following in your environment:

```
$ node -p 'new Promise((f, r) => f(42))'
Promise { 42 }
```

**Comment by klodoma** [comment]
node version: v0.10.25
```
root@9886acca1338:/producer# node --version
v0.10.25

```

Now, I've migrated the docker container to Ubuntu 16.04 and it seems to have fixed the problem. 
I'll dig further to gather a bit more info. 
It seems that 
`npm install es6-promise
`and putting this in the js also might work
`var Promise = require("es6-promise").Promise`

**Comment by cyrus-and** [comment]
Yup, that's the problem, native ES6 promises are not present in [v0.10.25](http://node.green/#Promise). IMHO updating to a more recent version of Node.js is better than using a polyfill.

I should probably state the minimum  required Node.js version in `package.json`.

**Comment by klodoma** [comment]
Thanks for the time and replies. I thought this is not a bug from your code, just I didn't know where to go :)
I'll close this.

**Comment by cyrus-and** [comment]
You're welcome!
I've added the check in the `package.json`, you should now get a warning if you use a version older than 0.12.15.
