### ISSUE TITLE
Cannot bundle with WebPack into single Node executable: "TypeError: r.mask is not a function"

### ISSUE THREAD

**Issue by slhck** [cyrus-and/chrome-remote-interface#501]
## Environment

| Component | Version
|-|-
| Node.js						| v16.16
| Client (Chrome/Chromium/...)	| Chrome 104
| OS running Node.js			| macOS
| OS running the client			| macOS
| chrome-remote-interface		| 0.31.3

Is the client running in a container? No

## Description

I am building a Node.js CLI app that bundles Selenium and uses it to instrument Chrome with ChromeDriver. This has worked fine so far. It's important that I can package the final app as one CommonJS file to be run directly with `node index.cjs`, with all dependencies bundled.

Now I want to integrate this project, and in a development environment (using `ts-node`), all works fine. Once I do the production build with WebPack, the following error is thrown – at some point when messages are being sent across the WebSocket:

```
TypeError: r.mask is not a function
    at mask (index.cjs:3:30244)
    at Function.frame (index.cjs:3:46854)
    at u.dispatch (index.cjs:3:48580)
    at u.send (index.cjs:3:48401)
    at C.send (index.cjs:3:59953)
    at e.exports._enqueueCommand (index.cjs:3:27709)
    at index.cjs:3:25511
    at new Promise (<anonymous>)
    at e.exports.send (index.cjs:3:25485)
    at Object.o [as evaluate] (index.cjs:3:23954)
```

The basic WebPack config is like this:

```js
export default {
  entry: './src/index.ts',
  target: 'node',
  mode: 'production',
  node: {
    __dirname: false,
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loader: 'ts-loader',
        exclude: /node_modules/,
        options: {
          // disable type checker - we will use it in fork plugin
          transpileOnly: true,
        },
      },
    ],
  },
  stats: {
    // Ignore warnings due to yarg's dynamic module loading
    warningsFilter: [/node_modules\/yargs/, /node_modules\/selenium-webdriver/],
  },
  resolve: {
    plugins: [new ResolveTypeScriptPlugin()],
    extensions: ['.tsx', '.cjs', '.ts', '.js', '.json'],
  },
  externals: {
    bufferutil: 'bufferutil',
    'utf-8-validate': 'utf-8-validate',
  },
  output: {
    filename: 'index.cjs',
    path: destPath,
  },
  plugins: [
    new CleanWebpackPlugin({ verbose: true }),
    new ForkTsCheckerWebpackPlugin(),
    new webpack.EnvironmentPlugin({
      NODE_ENV: 'development', // use 'development' unless process.env.NODE_ENV is defined
    }),
  ],
};

```

Note that I have two `externals` defined already, which I believe has something to do with the problem. I needed those originally to get the app working.

Selenium uses CDP in the background, so I am unsure why it breaks now when I use this project.

I also see that a similar issue was raised for [puppeteer](https://github.com/puppeteer/puppeteer/issues/8121), although I am unsure what I would have to do to fix this.

This happens both with Node 16.16.0 and Node 18.7.0.

Any idea?

**Comment by slhck** [comment]
Seems that adding this in the environment fixed it:

```js
    new webpack.EnvironmentPlugin({
      NODE_ENV: 'development', // use 'development' unless process.env.NODE_ENV is defined
      WS_NO_BUFFER_UTIL: 1,
      WS_NO_UTF_8_VALIDATE: 1,
    }),
```

Though I wonder why this issue hasn't surfaced before with the other packages that use WebSockets.
