### ISSUE TITLE
Unhandled errors, although everything is "packed" in Try-Catch

### ISSUE THREAD

**Issue by 0x7357** [cyrus-and/chrome-remote-interface#527]
I get these two errors even though **everything was "packed" into Try-Catch**. How can I catch these errors so that they do not terminate the complete program?

```
C:\Users\Administrator\Desktop\Project\node_modules\ws\lib\websocket.js:783
      abortHandshake(
      ^

Error: Unexpected server response: 500
    at ClientRequest.<anonymous> (C:\Users\Administrator\Desktop\Project\node_modules\ws\lib\websocket.js:783:7)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
    at Socket.socketOnData (node:_http_client:534:22)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

Node.js v18.12.1
```

```
C:\Users\Administrator\Desktop\Project\node_modules\chrome-remote-interface\lib\chrome.js:183
                return object.webSocketDebuggerUrl;
                              ^

TypeError: Cannot read properties of undefined (reading 'webSocketDebuggerUrl')
    at Chrome._fetchDebuggerURL (C:\Users\Administrator\Desktop\Project\node_modules\chrome-remote-interface\lib\chrome.js:183:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Chrome._start (C:\Users\Administrator\Desktop\Project\node_modules\chrome-remote-interface\lib\chrome.js:140:25)

Node.js v18.12.1
```

**Comment by cyrus-and** [comment]
You completely disregarded the pull request template, and didn't provide a way for me to reproduce this, how am I supposed to help you?
