### ISSUE TITLE
Node exited with WebSocket is not open: readyState 2 (CLOSING)

### ISSUE THREAD

**Issue by marcellinuskristanto** [cyrus-and/chrome-remote-interface#539]
## Environment

| Component | Version
|-|-
| Node.js						| v18.16.1
| Client (Chrome/Chromium/...)	| 114.0.5735.198-1_amd64
| OS running Node.js			| Ubuntu
| OS running the client			| Ubuntu
| chrome-remote-interface		| 0.32.2

Is the client running in a container? YES

## Description

Hello, I have this `doCrawl` function that will connect cdp to a chrome and crawl some site. My problem is sometimes my node app crashed with this log
```
/app/node_modules/chrome-remote-interface/node_modules/ws/lib/websocket.js:988
    const err = new Error(
                ^

Error: WebSocket is not open: readyState 2 (CLOSING)
    at sendAfterClose (/app/node_modules/chrome-remote-interface/node_modules/ws/lib/websocket.js:988:17)
    at WebSocket.send (/app/node_modules/chrome-remote-interface/node_modules/ws/lib/websocket.js:405:7)
    at Chrome._enqueueCommand (/app/node_modules/chrome-remote-interface/lib/chrome.js:301:18)
    at /app/node_modules/chrome-remote-interface/lib/chrome.js:88:22
    at new Promise (<anonymous>)
    at Chrome.send (/app/node_modules/chrome-remote-interface/lib/chrome.js:87:20)
    at Object.handler [as failRequest] (/app/node_modules/chrome-remote-interface/lib/api.js:33:23)
    at w.<anonymous> (/app/dist/server.js:1:25311)
    at Generator.next (<anonymous>)
    at /app/dist/server.js:1:21792

Node.js v18.16.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
i think the crash happen because of this listener `Fetch.requestPaused` run after the browser gets killed ? How can i prevent it from crashing my app ? i try putting try catch anywhere seems not helping, I also tried with `Network.requestIntercepted`, but also got same crash sometimes

## Example

```ts
const CDP = require('chrome-remote-interface');

async doCrawl(fn: (client: CDP.Client) => void) {
  const client = await CDP({
    port: 9000
  });

  // block image request
  const { Fetch } = client
  try {
    Fetch.requestPaused(async ({requestId, request}) => {
      await Fetch.failRequest({
        requestId,
        errorReason: 'Aborted'
      });
    });

    await Fetch.enable({
      patterns: [
        {urlPattern: "*", resourceType: "Image", requestStage: "Request"},
        {urlPattern: "*", resourceType: "Media", requestStage: "Request"},
      ]
    });
    
    // Network.requestIntercepted(({interceptionId, request}) => {
    //   Network.continueInterceptedRequest({
    //     interceptionId,
    //     errorReason: 'Aborted'
    //   });
    // });
    
    // await Network.enable()
    // await Network.setRequestInterception({
    //   patterns: [
    //     {urlPattern: "*", resourceType: "Image", interceptionStage: "Request"},
    //     {urlPattern: "*", resourceType: "Media", interceptionStage: "Request"},
    //   ]
    // })
  } catch(e) {
    console.error(e)
  }
  
  try {
    await fn(client)
  } catch(e) {
    console.error(e)
  } finally {
    try { await Fetch.disable() } catch(error){ console.error("Fetch.disable exception:", error) }
    try{ await client.close() } catch(error){ console.error("client.close exception:", error) }
  }
}
```

**Comment by cyrus-and** [comment]
I think you should handle the `Fetch.failRequest` exceptions as well:

```js
Fetch.requestPaused(async ({requestId, request}) => {
  try {
    await Fetch.failRequest({
      requestId,
      errorReason: 'Aborted'
    });
  } catch (err) {
    console.error(err)
  }
});
```

**Comment by cyrus-and** [comment]
`Fetch.requestPaused` if invoked that way will never throw any exception, it's an event handler.

**Comment by marcellinuskristanto** [comment]
hmm i miss that 😅, thank you for fast reply, i will try it first
