### ISSUE TITLE
 Error: Can only get response body on requests captured after headers received.

### ISSUE THREAD

**Issue by giudon010** [cyrus-and/chrome-remote-interface#548]
## Environment

| Component | Version
|-|-
| Node.js						| 14.16.0
| Client (Chrome/Chromium/...)	| 119.0.6045.160
| OS running Node.js			| Windows 11
| OS running the client			| Windows 11
| chrome-remote-interface		| 0.33.0

Is the client running in a container? NO

## Example

I am trying to fetch some resources but I get some of this errors (unhandled), that block requests:
```
(node:11468) UnhandledPromiseRejectionWarning: Error: Can only get response body on requests captured after headers received.
    at C:\Chrome_Remote_Interface\node_modules\chrome-remote-interface\lib\chrome.js:94:35
    at Chrome._handleMessage (C:\Chrome_Remote_Interface\node_modules\chrome-remote-interface\lib\chrome.js:272:17)
    at WebSocket.<anonymous> (C:\Chrome_Remote_Interface\node_modules\chrome-remote-interface\lib\chrome.js:240:22)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Chrome_Remote_Interface\node_modules\ws\lib\websocket.js:1068:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (C:\Chrome_Remote_Interface\node_modules\ws\lib\receiver.js:517:14)
    at Receiver.getData (C:\Chrome_Remote_Interface\node_modules\ws\lib\receiver.js:435:17)
    at Receiver.startLoop (C:\Chrome_Remote_Interface\node_modules\ws\lib\receiver.js:143:22)
    at Receiver._write (C:\Chrome_Remote_Interface\node_modules\ws\lib\receiver.js:78:10)
```

The following is the piece of code that throws exceptions:
![image](https://github.com/cyrus-and/chrome-remote-interface/assets/58396344/26edc8b1-b669-44e6-bedc-bb8dafaa7c81)

**Comment by giudon010** [comment]
The web resouce that have problem reply with a status code "302 Found"

**Comment by giudon010** [comment]
I just solved the problem.

It occurs because I was trying to call "await Network.getResponseBodyForInterception" on a page that doesn't have the body (status code was 302).
