### ISSUE TITLE
cannot close browser with out 

### ISSUE THREAD

**Issue by frenchghost** [cyrus-and/chrome-remote-interface#551]
Error: WebSocket connection closed
    at Chrome._handleConnectionClose (C:\Users\ethan\Desktop\shapeVelo\node_modules\chrome-remote-interface\lib\chrome.js:254:21)        
    at WebSocket.<anonymous> (C:\Users\ethan\Desktop\shapeVelo\node_modules\chrome-remote-interface\lib\chrome.js:243:22)
    at WebSocket.emit (node:events:390:28)
    at WebSocket.emitClose (C:\Users\ethan\Desktop\shapeVelo\node_modules\ws\lib\websocket.js:246:10)
    at Receiver.receiverOnFinish (C:\Users\ethan\Desktop\shapeVelo\node_modules\ws\lib\websocket.js:1058:20)
    at Receiver.emit (node:events:390:28)
    at finish (node:internal/streams/writable:750:10)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

   async close() {
      this.chrome.kill()
    }

**Comment by frenchghost** [comment]
also tried async close() {
    try {
        if (this.client) {
            await this.client.close();
        }
        if (this.chrome) {
            await this.chrome.kill();
        }
    } catch (err) {
        console.error('Error while closing:', err);
    }
}

**Comment by cyrus-and** [comment]
From the issue template you disregarded:

```
<!-- OMITTING THE FOLLOWING MIGHT CAUSE THIS ISSUE TO BE CLOSED WITHOUT NOTICE. -->
```
